apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-deployment # Deployment의 이름
  labels:
    app: todo-db # Deployment 자체의 레이블
spec:
  replicas: 1 # Pod 복제본 수
  selector:
    matchLabels:
      app: todo-db # 이 Deployment가 관리할 Pod를 선택하는 레이블
  template:
    metadata:
      labels:
        app: todo-db # Pod에 부여될 레이블
    spec:
      containers:
        - name: mysql # 컨테이너 이름
          image: mysql:8.0 # 사용할 Docker 이미지
          ports:
            - containerPort: 3306 # MySQL 기본 포트
          envFrom:
            - configMapRef:
                name: todo-db-config
            - secretRef:
                name: todo-db-secret
          env: # 환경 변수 설정
            - name: MYSQL_ROOT_PASSWORD
              value: "1234" # 실제 사용할 루트 비밀번호로 변경하세요!
